language: ruby
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-9
  - rbx
cache: bundler
sudo: false
matrix:
  allow_failures:
      - rvm: 2.2.2
      - rvm: jruby-9
      - rvm: rbx
