source 'http://rubygems.org'

gem 'rdf',            :git => 'git://github.com/bendiken/rdf.git'
gem 'rdf-isomorphic', :git => 'git://github.com/bhuga/rdf-isomorphic.git'
gem 'rdf-json',       :git => 'git://github.com/bendiken/rdf-json.git'
gem 'rdf-n3',         :git => 'git://github.com/gkellogg/rdf-n3.git'
gem 'rdf-rdfa',       :git => 'git://github.com/gkellogg/rdf-rdfa.git'
gem 'rdf-rdfxml',     :git => 'git://github.com/gkellogg/rdf-rdfxml.git'
gem 'rdf-trix',       :git => 'git://github.com/bendiken/rdf-trix.git'
