source 'http://rubygems.org'

gem 'rdf',            git: 'git://github.com/ruby-rdf/rdf.git'
gem 'rdf-isomorphic', git: 'git://github.com/ruby-rdf/rdf-isomorphic.git'
gem 'rdf-json',       git: 'git://github.com/ruby-rdf/rdf-json.git'
gem 'rdf-n3',         git: 'git://github.com/ruby-rdf/rdf-n3.git'
gem 'rdf-rdfa',       git: 'git://github.com/ruby-rdf/rdf-rdfa.git'
gem 'rdf-rdfxml',     git: 'git://github.com/ruby-rdf/rdf-rdfxml.git'
gem 'rdf-trix',       git: 'git://github.com/ruby-rdf/rdf-trix.git'
